// src/components/Header.tsx
import React from 'react';
import { useTheme } from '../context/ThemeContext';
import './Header.css';

interface HeaderProps {
  activeTab: string;
  setActiveTab: (tab: string) => void;
}

const Header: React.FC<HeaderProps> = ({ activeTab, setActiveTab }) => {
  const { theme, toggleTheme } = useTheme();
  const tabs = [
    'Overview',
    'Daily Notes',
    'Novels/Fiction',
    'Journals',
    'Research',
    'Articles/Blogs',
    'Meetings',
    'Tasks/Todos',
    'Books/Reading',
    'Code Snippets',
    'Brainstorming',
  ];

  return (
    <header className="header">
      <div className="header-top">
        <div className="logo">
          <span className="material-symbols-outlined logo-icon">nutrition</span>
          <span className="logo-text">ENVELLO</span>
        </div>
        <div className="header-search">
          <span className="material-symbols-outlined search-icon">search</span>
          <input
            type="text"
            placeholder="Quick find (Cmd + K)"
            className="search-input"
          />
        </div>
        <div className="header-actions">
          <button className="btn-new-project">
            <span className="material-symbols-outlined btn-icon-inner">add</span> New Project
          </button>
          <div className="divider-vertical"></div>
          <button className="icon-btn">
            <span className="material-symbols-outlined">notifications</span>
          </button>
          <button className="icon-btn" onClick={toggleTheme} title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} Mode`}>
            <span className="material-symbols-outlined">
              {theme === 'dark' ? 'light_mode' : 'dark_mode'}
            </span>
          </button>
          <button className="icon-btn">
            <span className="material-symbols-outlined">settings</span>
          </button>
          <div className="profile-menu">
            <div className="profile-avatar"></div>
          </div>
        </div>
      </div>
      <nav className="header-nav">
        {tabs.map((tab) => (
          <button
            key={tab}
            className={`nav-tab ${activeTab === tab ? 'active' : ''}`}
            onClick={() => setActiveTab(tab)}
          >
            {tab}
          </button>
        ))}
      </nav>
    </header>
  );
};

export default Header;

// src/app/components/layout/header/header.component.ts
import { Component, Input, inject, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ThemeService, Theme } from '../../../services/theme.service';
import { Router } from '@angular/router';
import { QuickFindComponent } from '../../quick-find/quick-find.component';
import { AddNewModalComponent } from '../../add-new-modal/add-new-modal.component';
import { SettingsModalComponent } from '../../settings-modal/settings-modal.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, QuickFindComponent, AddNewModalComponent, SettingsModalComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  @Input() activeTab = 'Overview';
  @ViewChild(QuickFindComponent) quickFind?: QuickFindComponent;
  @ViewChild(AddNewModalComponent) addNewModal?: AddNewModalComponent;
  @ViewChild(SettingsModalComponent) settingsModal?: SettingsModalComponent;

  themeService = inject(ThemeService);
  private router = inject(Router);

  tabs = [
    'Overview',
    'Daily Notes',
    'Novels/Fiction',
    'Journals',
    'Research',
    'Articles/Blogs',
    'Meetings',
    'Tasks/Todos',
    'Books/Reading',
    'Code Snippets',
    'Brainstorming',
  ];

  get theme(): Theme {
    return this.themeService.theme();
  }

  getThemeIcon(): string {
    const theme = this.theme;
    if (theme === 'dark') return 'dark_mode';
    if (theme === 'light') return 'light_mode';
    return 'palette'; // colorful theme
  }

  getNextTheme(): string {
    const theme = this.theme;
    if (theme === 'dark') return 'Light';
    if (theme === 'light') return 'Colorful';
    return 'Dark';
  }

  toggleTheme() {
    this.themeService.toggleTheme();
  }

  navigateTo(tab: string) {
    // Map tab name back to route path
    const map: Record<string, string> = {
      'Overview': 'overview',
      'Novels/Fiction': 'novels',
      'Research': 'research',
      'Articles/Blogs': 'articles',
      'Journals': 'journals',
      'Daily Notes': 'daily-notes',
      'Tasks/Todos': 'tasks',
      'Meetings': 'meetings',
      'Books/Reading': 'books',
      'Code Snippets': 'snippets',
      'Brainstorming': 'brainstorming'
    };
    const path = map[tab] || 'overview';
    this.router.navigate([path]);
  }

  openQuickFind() {
    this.quickFind?.open();
  }

  openAddNew() {
    this.addNewModal?.open();
  }

  openSettings() {
    this.settingsModal?.open();
  }
}

<header class="header">
    <div class="header-top">
        <div class="logo">
            <span class="material-symbols-outlined logo-icon">nutrition</span>
            <span class="logo-text">ENVELLO</span>
        </div>
        <div class="header-search" (click)="openQuickFind()">
            <span class="material-symbols-outlined search-icon">search</span>
            <input type="text" placeholder="Quick find (Cmd + K)" class="search-input" readonly />
        </div>
        <div class="header-actions">
            <button class="btn-new-project" (click)="openAddNew()">
                <span class="material-symbols-outlined btn-icon-inner">add</span> <span>Add New</span>
            </button>
            <div class="divider-vertical"></div>
            <button class="icon-btn">
                <span class="material-symbols-outlined">notifications</span>
            </button>
            <button class="icon-btn" (click)="toggleTheme()" [title]="'Switch to ' + getNextTheme() + ' Mode'">
                <span class="material-symbols-outlined">
                    {{ getThemeIcon() }}
                </span>
            </button>
            <button class="icon-btn" (click)="openSettings()">
                <span class="material-symbols-outlined">settings</span>
            </button>
            <div class="profile-menu">
                <div class="profile-avatar"></div>
            </div>
        </div>
    </div>
    <nav class="header-nav">
        @for (tab of tabs; track tab) {
        <button class="nav-tab" [class.active]="activeTab === tab" (click)="navigateTo(tab)">
            {{ tab }}
        </button>
        }
    </nav>
</header>

<!-- Quick Find Modal -->
<app-quick-find></app-quick-find>

<!-- Add New Modal -->
<app-add-new-modal></app-add-new-modal>

<!-- Settings Modal -->
<app-settings-modal></app-settings-modal>
