// src/components/Footer.tsx
import React from 'react';
import './Footer.css';

const Footer: React.FC = () => {
  return (
    <footer className="footer">
      <div className="footer-item">
        <span className="footer-icon">🔥</span>
        <span className="footer-label">CURRENT STREAK:</span>
        <span className="footer-value">14 Days</span>
        <div className="streak-indicators">
          <span className="streak-dot active"></span>
          <span className="streak-dot active"></span>
          <span className="streak-dot active"></span>
          <span className="streak-dot"></span>
        </div>
      </div>
      <div className="footer-item">
        <span className="status-dot"></span>
        <span className="footer-label">SYSTEM OPERATIONAL</span>
      </div>
      <div className="footer-item">
        <span className="footer-icon">☁️</span>
        <span className="footer-label">2.4 GB / 50 GB CORPORATE</span>
      </div>
      <div className="footer-item">
        <span className="footer-icon">📅</span>
        <span className="footer-label">Writing Consistency: 89% (Last 30 Days)</span>
      </div>
      <div className="footer-item">
        <span className="footer-label">V5.0-ENTERPRISE PM</span>
        <span className="footer-separator">•</span>
        <span className="footer-label">Session: 04:12:33</span>
      </div>
    </footer>
  );
};

export default Footer;

// src/app/components/layout/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent { }

<footer class="footer">
    <div class="footer-item">
        <span class="material-symbols-outlined footer-icon">local_fire_department</span>
        <span class="footer-label">CURRENT STREAK:</span>
        <span class="footer-value">14 Days</span>
        <div class="streak-indicators">
            <span class="streak-dot active"></span>
            <span class="streak-dot active"></span>
            <span class="streak-dot active"></span>
            <span class="streak-dot"></span>
        </div>
    </div>
    <div class="footer-item">
        <span class="status-dot"></span>
        <span class="footer-label">SYSTEM OPERATIONAL</span>
    </div>
    <div class="footer-item">
        <span class="material-symbols-outlined footer-icon">cloud</span>
        <span class="footer-label">2.4 GB / 50 GB CORPORATE</span>
    </div>
    <div class="footer-item">
        <span class="material-symbols-outlined footer-icon">calendar_today</span>
        <span class="footer-label">Writing Consistency: 89% (Last 30 Days)</span>
    </div>
    <div class="footer-item">
        <span class="footer-label">V5.0-ENTERPRISE PM</span>
        <span class="footer-separator">•</span>
        <span class="footer-label">Session: 04:12:33</span>
    </div>
</footer>
