// src-react/components/ProjectOversight.tsx
import React, { useState } from 'react';
import './ProjectOversight.css';

interface Project {
  id: string;
  title: string;
  status: 'DRAFTING' | 'PLANNING' | 'COMPLETE' | 'REVIEW';
  words: string;
  updated: string;
  icon: string;
}

const ProjectOversight: React.FC = () => {
  const [projects] = useState<Project[]>([
    {
      id: '1',
      title: 'Project Alpha: Final Manuscript',
      status: 'DRAFTING',
      words: '48.2k',
      updated: '2m ago',
      icon: 'menu_book',
    },
    {
      id: '2',
      title: 'Neon Orchard Chronicles',
      status: 'PLANNING',
      words: '12.5k',
      updated: '1h ago',
      icon: 'description',
    },
    {
      id: '3',
      title: 'The Scent of Green',
      status: 'COMPLETE',
      words: '82.1k',
      updated: 'Oct 24',
      icon: 'check_circle',
    },
    {
      id: '4',
      title: 'Echoes of the Void',
      status: 'REVIEW',
      words: '35.0k',
      updated: '2d ago',
      icon: 'extension',
    },
  ]);

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'DRAFTING':
        return 'status-yellow';
      case 'PLANNING':
        return 'status-blue';
      case 'COMPLETE':
        return 'status-green';
      case 'REVIEW':
        return 'status-orange';
      default:
        return 'status-gray';
    }
  };

  return (
    <div className="project-oversight">
      <div className="section-header">
        <div className="section-title">
          <span className="material-symbols-outlined section-icon">list</span>
          PROJECT OVERSIGHT
        </div>
        <div className="section-controls">
          <button className="control-btn">All Status</button>
          <button className="control-btn">
            Sort by: Last Updated <span className="material-symbols-outlined filter-icon">expand_more</span>
          </button>
          <button className="control-btn icon-only">
            <span className="material-symbols-outlined">search</span>
          </button>
        </div>
      </div>
      <div className="project-table">
        <div className="table-header">
          <div className="col-title">PROJECT TITLE</div>
          <div className="col-status">STATUS</div>
          <div className="col-words">WORDS</div>
          <div className="col-updated">UPDATED</div>
        </div>
        <div className="table-body">
          {projects.map((project) => (
            <div key={project.id} className="table-row">
              <div className="col-title">
                <span className="material-symbols-outlined project-icon">{project.icon}</span>
                {project.title}
              </div>
              <div className="col-status">
                <span className={`status-badge ${getStatusColor(project.status)}`}>
                  {project.status}
                </span>
              </div>
              <div className="col-words">{project.words}</div>
              <div className="col-updated">{project.updated}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ProjectOversight;

// apps/web/src/app/components/dashboard/project-oversight/project-oversight.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BadgeComponent, BadgeVariant } from '@envello/ui';

interface Project {
  id: string;
  title: string;
  status: 'DRAFTING' | 'PLANNING' | 'COMPLETE' | 'REVIEW';
  words: string;
  updated: string;
  icon: string;
}

@Component({
  selector: 'app-project-oversight',
  standalone: true,
  imports: [CommonModule, BadgeComponent],
  templateUrl: './project-oversight.component.html',
  styleUrl: './project-oversight.component.css'
})
export class ProjectOversightComponent {
  projects = signal<Project[]>([
    {
      id: '1',
      title: 'Project Alpha: Final Manuscript',
      status: 'DRAFTING',
      words: '48.2k',
      updated: '2m ago',
      icon: 'menu_book',
    },
    {
      id: '2',
      title: 'Neon Orchard Chronicles',
      status: 'PLANNING',
      words: '12.5k',
      updated: '1h ago',
      icon: 'description',
    },
    {
      id: '3',
      title: 'The Scent of Green',
      status: 'COMPLETE',
      words: '82.1k',
      updated: 'Oct 24',
      icon: 'check_circle',
    },
    {
      id: '4',
      title: 'Echoes of the Void',
      status: 'REVIEW',
      words: '35.0k',
      updated: '2d ago',
      icon: 'extension',
    },
  ]);

  getStatusVariant(status: string): BadgeVariant {
    switch (status) {
      case 'DRAFTING': return 'warning';
      case 'PLANNING': return 'info';
      case 'COMPLETE': return 'success';
      case 'REVIEW':   return 'accent';
      default:         return 'default';
    }
  }
}

<div class="project-oversight flex flex-col">
    <div class="section-header flex items-center justify-between">
        <div class="section-title flex items-center gap-2">
            <span class="material-symbols-outlined section-icon">list</span>
            PROJECT OVERSIGHT
        </div>
        <div class="section-controls flex items-center gap-2">
            <button class="control-btn">All Status</button>
            <button class="control-btn">
                Sort by: Last Updated <span class="material-symbols-outlined filter-icon">expand_more</span>
            </button>
            <button class="control-btn icon-only">
                <span class="material-symbols-outlined">search</span>
            </button>
        </div>
    </div>
    <div class="project-table">
        <div class="table-header">
            <div class="col-title">PROJECT TITLE</div>
            <div class="col-status">STATUS</div>
            <div class="col-words">WORDS</div>
            <div class="col-updated">UPDATED</div>
        </div>
        <div class="table-body">
            @for (project of projects(); track project.id) {
            <div class="table-row flex items-center">
                <div class="col-title">
                    <span class="material-symbols-outlined project-icon">{{ project.icon }}</span>
                    {{ project.title }}
                </div>
                <div class="col-status">
                    <span class="status-badge" [class]="getStatusColor(project.status)">
                        {{ project.status }}
                    </span>
                </div>
                <div class="col-words">{{ project.words }}</div>
                <div class="col-updated">{{ project.updated }}</div>
            </div>
            }
        </div>
    </div>
</div>
