// apps/web/src/app/components/layout/header/header.component.ts
import { Component, Input, inject, ViewChild, signal, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ThemeService, Theme } from '../../../services/theme.service';
import { NotificationService } from '../../../services/notification.service';
import { UserService } from '../../../services/user.service';
import { Router } from '@angular/router';
import { QuickFindComponent } from '../../quick-find/quick-find.component';
import { AddNewModalComponent } from '../../add-new-modal/add-new-modal.component';
import { SettingsModalComponent } from '../../settings-modal/settings-modal.component';
import { NotificationCenterComponent } from '../../notification-center/notification-center.component';
import { ProfileMenuComponent } from '../../profile-menu/profile-menu.component';
import { ProfileEditorComponent } from '../../profile-editor/profile-editor.component';
import { EnvLogoComponent } from '../../../shared/ui/logo/logo.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, QuickFindComponent, AddNewModalComponent, SettingsModalComponent, NotificationCenterComponent, ProfileMenuComponent, ProfileEditorComponent, EnvLogoComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit, OnDestroy {
  @Input() activeTab = 'Overview';
  @Input() isImmersive = false;
  @Output() sidebarCollapsedChange = new EventEmitter<boolean>();
  @ViewChild(QuickFindComponent) quickFind?: QuickFindComponent;
  @ViewChild(AddNewModalComponent) addNewModal?: AddNewModalComponent;
  @ViewChild(SettingsModalComponent) settingsModal?: SettingsModalComponent;
  @ViewChild(NotificationCenterComponent) notificationCenter?: NotificationCenterComponent;
  @ViewChild(ProfileMenuComponent) profileMenu?: ProfileMenuComponent;
  @ViewChild(ProfileEditorComponent) profileEditor?: ProfileEditorComponent;

  themeService = inject(ThemeService);
  notificationService = inject(NotificationService);
  userService = inject(UserService);
  private router = inject(Router);

  // Expose signals for template
  unreadCount = this.notificationService.unreadCount;
  userInitials = this.userService.userInitials;

  // Navigation layout: 'vertical' | 'horizontal' | 'minimized'
  navigationLayout = signal<'vertical' | 'horizontal' | 'minimized'>('minimized');

  // Sidebar state - default to collapsed (minimized)
  sidebarCollapsed = signal(true);

  private navigationLayoutListener?: (event: CustomEvent) => void;
  private previousLayout?: 'vertical' | 'horizontal' | 'minimized';

  tabs = [
    'Overview',
    'Tasks/Todos',
    'Daily Notes',
    'Novels/Fiction',
    'Journals',
    'Research',
    'Articles/Blogs',
    'Meetings',
    'Books/Reading',
    'Code Snippets',
  ];

  // Icon mapping for each tab
  tabIcons: Record<string, string> = {
    'Overview': 'dashboard',
    'Daily Notes': 'note',
    'Novels/Fiction': 'menu_book',
    'Journals': 'book',
    'Research': 'science',
    'Articles/Blogs': 'article',
    'Meetings': 'groups',
    'Tasks/Todos': 'checklist',
    'Books/Reading': 'auto_stories',
    'Code Snippets': 'code',
  };

  get theme(): Theme {
    return this.themeService.theme();
  }

  getThemeIcon(): string {
    const theme = this.theme;
    if (theme === 'dark') return 'dark_mode';
    if (theme === 'light') return 'light_mode';
    return 'palette'; // colorful theme
  }

  getNextTheme(): string {
    const theme = this.theme;
    if (theme === 'dark') return 'Light';
    if (theme === 'light') return 'Colorful';
    return 'Dark';
  }

  toggleTheme() {
    this.themeService.toggleTheme();
  }

  navigateTo(tab: string) {
    // Map tab name back to route path
    const map: Record<string, string> = {
      'Overview': 'overview',
      'Novels/Fiction': 'novels',
      'Research': 'research',
      'Articles/Blogs': 'articles',
      'Journals': 'journals',
      'Daily Notes': 'daily-notes',
      'Tasks/Todos': 'tasks',
      'Meetings': 'meetings',
      'Books/Reading': 'books',
      'Code Snippets': 'snippets',
    };
    const path = map[tab] || 'overview';
    this.router.navigate([path]);
  }

  openQuickFind() {
    this.quickFind?.open();
  }

  openAddNew() {
    this.addNewModal?.open();
  }

  openSettings() {
    this.settingsModal?.open();
  }

  openNotifications() {
    this.notificationCenter?.toggle();
  }

  openProfileMenu() {
    this.profileMenu?.toggle();
  }

  handleOpenSettings() {
    this.settingsModal?.open();
  }

  handleOpenProfile() {
    this.profileEditor?.open();
  }

  toggleSidebar() {
    // Allow toggling in both minimized and vertical modes
    if (this.navigationLayout() === 'minimized' || this.navigationLayout() === 'vertical') {
      this.sidebarCollapsed.set(!this.sidebarCollapsed());
      this.sidebarCollapsedChange.emit(this.sidebarCollapsed());
    }
  }

  getTabIcon(tab: string): string {
    return this.tabIcons[tab] || 'circle';
  }

  ngOnInit() {
    // Load navigation layout from localStorage
    this.loadNavigationLayout();

    // Listen for navigation layout changes from settings
    this.navigationLayoutListener = (event: CustomEvent) => {
      this.navigationLayout.set(event.detail);
      this.applyNavigationLayout();
    };
    window.addEventListener('navigationLayoutChanged', this.navigationLayoutListener as EventListener);

    // Apply initial layout
    this.applyNavigationLayout();
  }

  ngOnDestroy() {
    if (this.navigationLayoutListener) {
      window.removeEventListener('navigationLayoutChanged', this.navigationLayoutListener as EventListener);
    }
  }

  private loadNavigationLayout() {
    const saved = localStorage.getItem('envello-settings');
    if (saved) {
      try {
        const settings = JSON.parse(saved);
        this.navigationLayout.set(settings.navigationLayout || 'minimized');
      } catch (e) {
        console.error('Failed to load navigation layout:', e);
      }
    }
  }

  private applyNavigationLayout() {
    const layout = this.navigationLayout();

    // Only set initial state when layout actually changes, not on every call
    if (this.previousLayout !== layout) {
      if (layout === 'minimized') {
        // Start collapsed in minimized mode, but allow user to expand via toggle
        this.sidebarCollapsed.set(true);
      } else if (layout === 'vertical') {
        // Start expanded in vertical mode, but allow user to collapse via toggle
        this.sidebarCollapsed.set(false);
      }
      // For horizontal, sidebar is not shown

      this.previousLayout = layout;
      this.sidebarCollapsedChange.emit(this.sidebarCollapsed());
    }
  }
}

<div class="header-wrapper">
    <header class="header">
        <div class="header-top flex items-center justify-between gap-4">
            <div class="logo flex items-center gap-2">
                <env-logo height="28px"></env-logo>
            </div>
            <div class="header-search" (click)="openQuickFind()">
                <span class="material-symbols-outlined search-icon">search</span>
                <input type="text" placeholder="Quick find (Cmd + K)" class="search-input" readonly />
            </div>
            <div class="header-actions flex items-center gap-2">
                <button class="btn-new-project" (click)="openAddNew()">
                    <span class="material-symbols-outlined btn-icon-inner">add</span> <span>Add New</span>
                </button>
                <div class="divider-vertical"></div>
                <button class="icon-btn notification-btn" (click)="openNotifications()">
                    <span class="material-symbols-outlined">notifications</span>
                    @if (unreadCount() > 0) {
                    <span class="notification-badge">{{ unreadCount() }}</span>
                    }
                </button>
                <button class="icon-btn" (click)="toggleTheme()" [title]="'Switch to ' + getNextTheme() + ' Mode'">
                    <span class="material-symbols-outlined">
                        {{ getThemeIcon() }}
                    </span>
                </button>
                <div class="profile-menu" (click)="openProfileMenu()">
                    <div class="profile-avatar">
                        <span class="avatar-text">{{ userInitials() }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @if (!isImmersive) {
    @if (navigationLayout() === 'horizontal') {
    <!-- Horizontal Navigation -->
    <nav class="header-nav">
        @for (tab of tabs; track tab) {
        <button class="nav-tab" [class.active]="activeTab === tab" (click)="navigateTo(tab)">
            {{ tab }}
        </button>
        }
    </nav>
    } @else {
    <!-- Vertical Sidebar -->
    <aside class="sidebar" [class.collapsed]="sidebarCollapsed()">
        <nav class="sidebar-nav">
            @for (tab of tabs; track tab) {
            <button class="sidebar-nav-item" [class.active]="activeTab === tab" (click)="navigateTo(tab)"
                [title]="sidebarCollapsed() ? tab : ''">
                <span class="material-symbols-outlined sidebar-icon">{{ getTabIcon(tab) }}</span>
                @if (!sidebarCollapsed()) {
                <span class="sidebar-label">{{ tab }}</span>
                }
            </button>
            }
        </nav>
        @if (navigationLayout() === 'vertical' || navigationLayout() === 'minimized') {
        <button class="sidebar-toggle" (click)="toggleSidebar()"
            [title]="sidebarCollapsed() ? 'Expand sidebar' : 'Collapse sidebar'">
            <span class="material-symbols-outlined">
                {{ sidebarCollapsed() ? 'chevron_right' : 'chevron_left' }}
            </span>
        </button>
        }
    </aside>
    }
    }
</div>

<!-- Quick Find Modal -->
<app-quick-find></app-quick-find>

<!-- Add New Modal -->
<app-add-new-modal></app-add-new-modal>

<!-- Settings Modal -->
<app-settings-modal></app-settings-modal>

<!-- Notification Center -->
<app-notification-center></app-notification-center>

<!-- Profile Menu -->
<app-profile-menu (onOpenSettings)="handleOpenSettings()" (onOpenProfile)="handleOpenProfile()">
</app-profile-menu>

<!-- Profile Editor -->
<app-profile-editor></app-profile-editor>

// src/components/Header.tsx
import React from 'react';
import { useTheme } from '../context/ThemeContext';
import './Header.css';

interface HeaderProps {
  activeTab: string;
  setActiveTab: (tab: string) => void;
}

const Header: React.FC<HeaderProps> = ({ activeTab, setActiveTab }) => {
  const { theme, toggleTheme } = useTheme();
  const tabs = [
    'Overview',
    'Daily Notes',
    'Novels/Fiction',
    'Journals',
    'Research',
    'Articles/Blogs',
    'Meetings',
    'Tasks/Todos',
    'Books/Reading',
    'Code Snippets',
    'Brainstorming',
  ];

  return (
    <header className="header">
      <div className="header-top">
        <div className="logo">
          <span className="material-symbols-outlined logo-icon">nutrition</span>
          <span className="logo-text">ENVELLO</span>
        </div>
        <div className="header-search">
          <span className="material-symbols-outlined search-icon">search</span>
          <input
            type="text"
            placeholder="Quick find (Cmd + K)"
            className="search-input"
          />
        </div>
        <div className="header-actions">
          <button className="btn-new-project">
            <span className="material-symbols-outlined btn-icon-inner">add</span> New Project
          </button>
          <div className="divider-vertical"></div>
          <button className="icon-btn">
            <span className="material-symbols-outlined">notifications</span>
          </button>
          <button className="icon-btn" onClick={toggleTheme} title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} Mode`}>
            <span className="material-symbols-outlined">
              {theme === 'dark' ? 'light_mode' : 'dark_mode'}
            </span>
          </button>
          <button className="icon-btn">
            <span className="material-symbols-outlined">settings</span>
          </button>
          <div className="profile-menu">
            <div className="profile-avatar"></div>
          </div>
        </div>
      </div>
      <nav className="header-nav">
        {tabs.map((tab) => (
          <button
            key={tab}
            className={`nav-tab ${activeTab === tab ? 'active' : ''}`}
            onClick={() => setActiveTab(tab)}
          >
            {tab}
          </button>
        ))}
      </nav>
    </header>
  );
};

export default Header;
